### ISSUE TITLE
Refactor duplicate code for Work Report and Home Detail view

### ISSUE THREAD

**Issue by brylie** [GeriLife/caregiving#19]
The Work Report and Home Detail view contain a significant amount of duplicated code. However, the code contains subtle changes, due to filtering the work reports on the Home Detail view.

## Task

- [ ] determine how to share code/queries between the Work Report and Home Detail view
- [ ] create a new app called `analytics` or `reports`
- [ ] move the shared code to the new app
- [ ] make changes to the code so it can be shared across the two views
