### ISSUE TITLE
Add initial "Duties" prototype

### ISSUE THREAD

**Issue by brylie** [GeriLife/caregiving#2]
We want to raise awareness about caregiving duties. To that end, we need a streamlined way for users to record duties.

## Duty model

The Duty model might contain the following fields:

- uuid: a unique ID for the Duty instance, alternatively consider using big ID, if that is sufficient
- type: the type of Duty, with default CHOICES
- caregiver: the User who completed the task, consider whether an intermediary model would be useful instead of using the User model directly
    - alternatively, extend the User model with an `is_caregiver` attribute, useful for filtering and distinguishing between types of users (staff, administrator, etc.) 
- caregiver_role: the role of the Caregiver who completed the task, with predefined CHOICES
- date: the date the Duty was completed
- time: the time the Duty was completed
- timezone: the timezone where the Duty was completed, used for accurate display and analytics
- created_by: the `user` that created the Duty instance
- created: the DateTime (in UTC) when the Duty instance was created

## Extended Duty model

If the above Duty model is fairly easy to achieve, consider extending the Duty model as part of this task to include the following fields. Otherwise, the relationships can be continued in a subsequent task.

- home: the related Home where the Duty was completed

## Task

- [x] add initial Duties app
- [x] define options for `duty type`
- [x] add localization to pre-defined data, where possible
- [x] determine the minimum-viable approach for date/time data with timezone support
- [x] consider adding relationships to the Home and Caregivers models from the Duty model
