### ISSUE TITLE
Enable localization

### ISSUE THREAD

**Issue by brylie** [GeriLife/caregiving#26]
Users need to see application text in their native language. To this end, we will add internationalization to all default texts. Once the texts are internationalized, we will have a localization process to translate the texts into supported languages.

## Task

- [ ] ensure all UI texts are internationalized
- [ ] ensure users can select from enabled languages
- [ ] localize UI texts into initial language(s)
