### ISSUE TITLE
Add a dark/light mode toggle switch on navbar

### ISSUE THREAD

**Issue by brylie** [GeriLife/caregiving#37]
Now that Bootstrap 5.3 supports dark and light mode and we have set the dark mode on our base `html` element, we can allow users to toggle their preferred mode.

## Task

- [ ] add a button, icon, or toggle widget on the navbar to allow users to toggle between dark and light mode
- [ ] bonus: user preference is saved across sessions (e.g., localstorage?)
- [ ] bonus: users can save their preference on a "my preferences" page when logged in (this is a stretch goal, so don't worry about it for now)

## Resources

- https://stackoverflow.com/questions/63082529/how-to-properly-introduce-a-light-dark-mode-in-bootstrap

**Comment by adrienneli104** [comment]
Hey could I be assigned this issue? I would love to contribute!

**Comment by adrienneli104** [comment]
Thanks! Would you also be able to assign this issue to @Icyviolet23, @TBennur, and @kc12341? We are a group of university students and would like to implement this feature and the bonus ones as a team.

**Comment by brylie** [comment]
I can only assign them if they comment in this issue discussion, since GitHub is only showing me the names of people who have commented.

**Comment by Icyviolet23** [comment]
I am on Adrienne's team and would like to be assigned to this issue!

**Comment by TBennur** [comment]
Hi, I am on Adrienne's team and would like to be assigned to this issue!

**Comment by kc12341** [comment]
Hi, I'm also on Adrienne's team and would like to be assigned to this issue!

**Comment by brylie** [comment]
Great work so far on the Dark/Light toggle. I've added some comments on the PR.
