### ISSUE TITLE
Determine how to group homes together and create initial Homes page

### ISSUE THREAD

**Issue by brylie** [GeriLife/caregiving#39]
Determine how we want to group homes, such as the allowed hierarchy level. After doing so, use the previous Homes display as inspiration to design new data visualizations for the new homes list display.

## Task

- [ ] create `HomeGroup` model
    - [ ] add `name` field to `HomeGroup` model
- [ ] add `group` field to `Home` model as a `ForeignKey` to `HomeGroup`
- [ ] add `group` field to `HomeForm` so homes can be assigned to groups
- [ ] create `Homes` view that lists homes
    - [ ]   homes should be grouped by group
    - [ ] if homes aren't part of a group, they will be displayed below grouped homes

## Example listing

- Group A
    - Home A
    - Home B
- Group B
    - Home C
    - Home D
- Home E (no group)   

## Reference screen

Note: you don't need to build the following data visualizations. This screen is only a visual reference to show the homes nested within home groups.

![image](https://github.com/GeriLife/caregiving/assets/17307/7563876a-a94a-4e12-bb55-1c4d69104ecf)
